# Create simple CI/CD pipeline
name: Simple CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
    
    - name: Run Tests
      run: npm test
    
    - name: Build Docker Image
      run: docker build -t my-devops-app .
    
    - name: Test Docker Container
      run: |
        docker run -d -p 3000:3000 --name test-container my-devops-app
        sleep 5
        curl -f http://localhost:3000/health || exit 1
        docker stop test-container
    
    - name: Deploy Success
      run: echo "🚀 Deployment successful!"